---
title: "HS_Skin_IL1B_expression"
author: "Neha Chaudhary"
date: "5/18/2023"
output: html_document
---

## IL1B Expression in HS Skin Visium Sections

```{r setup, include=FALSE}
### Step 1) Setup the environment and load necessary libraries
library(knitr)
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	cache = FALSE,
	cache.lazy = FALSE
)
library(Seurat)
library(ggplot2)
```


```{r Loaddata}
# Load the Seurat object from an RDS file
Data <- readRDS("Data_object.rds")  # Load preprocessed data object

# Optionally assign 'hs_all' object to 'Data' if needed
Data <- hs_all  # Assign hs_all to Data for downstream analysis (if desired)

gene <- "IL1B"  # Specify the gene of interest for downstream analysis

# DefaultAssay(Data) <- "Spatial"  # Optionally set assay to 'Spatial' if needed (currently commented out)

# Get unique sample names from metadata
imagenames <- unique(Data$sample)  # Extract unique sample identifiers
imagenames <- paste0("X", imagenames)  # Prefix each sample name with 'X' for consistency

# Set the cell identities to the 'annotation' column for further subsetting/analysis
Idents(Data) <- "annotation"  # Set cell identities to cell type or cluster annotation"
```



```{r plots, echo=FALSE, fig.height=7, fig.width=14}

for(i in 1:53){
  # Plot H&E image without legend, set transparency (alpha=0) and add a title
  a <- SpatialDimPlot(Data, images = imagenames[i], alpha = 0) + 
       ggtitle(paste(imagenames[i], "H&E", sep = "_")) + NoLegend()

  # Plot annotated clusters for the same image with legend and title
  b <- SpatialDimPlot(Data, images = imagenames[i]) + 
       ggtitle(paste(imagenames[i], "Annotation", sep = "_"))

  # Subset data object for current sample (remove 'X' prefix to match sample name)
  data1 <- subset(x = Data, subset = sample == gsub("X", "", imagenames[i]))

  # Set the limits for color scaling the feature plot
  min_lim <- 0  # Minimum value for IL1B expression
  max_lim <- signif(max(data1@assays$SCT["IL1B",]), 2)  # Maximum TNF expression for current sample, rounded to 2 significant digits

  # Create a spatial feature plot for gene expression ('IL1B') with custom color gradient and dynamic limits
  c <- SpatialFeaturePlot(Data, features = c(gene), images = imagenames[i]) + 
       scale_fill_gradient2(low = "navyblue", mid = "green", high = "yellow", 
                            midpoint = (max_lim - min_lim)/2, space = "Lab", na.value = "grey50", 
                            guide = "colourbar", aesthetics = "fill", limits = c(min_lim, max_lim))

  # Display all three plots side by side (H&E, annotation, IL1B expression)
  plot(a | b | c)
}

```
