---
title: "Hs_integrated_single_cell_analysis"
author: "Neha Chaudhary"
date: "9/29/2022"
output: html_document
---


```{r setup, echo = FALSE, results=FALSE, message=FALSE, warning=FALSE}
library(knitr)
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	cache = TRUE,
	cache.lazy = FALSE
)
library(SingleCellExperiment)
library(Seurat)
library(tidyverse)
library(kableExtra)
library(magick)
#library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)
library(xlsx)

```


```{r read_data for each study}
##SINGLE CELL WORKFLOW with example for GSE154775/HS1/ and HS2

#read metadata - count be excel/text
metadata <- read.xlsx("GSE154775_series_matrix.xlsx", sheetIndex = 1)

#read tha data
#location of folder generated by cell Ranger
Data <- Read10X("GSE154775/HS1/")

#create seurat object
GSE154775_HS_1 <- CreateSeuratObject(counts = Data,project = "GSE154775", min.cells = 3, min.features = 200)

# add all relevent metadata - source, tissue, methd of extraction,etc
GSE154775_HS_1$sample <- "GSE154775_HS_1"
GSE154775_HS_1$sample_details <- metadata$Sample_characteristics_ch1[1]
GSE154775_HS_1$sample_sources <- metadata$Sample_source_name_ch1[1]

#DO THIS FOR ALL DATASET/SAMPLES  WE WANT TO INTEGRATE

#read dataset 2
Data <- Read10X("/sc/wo/tri_data/nc/2022_09_HS_single_cell_RNA_seq_combined/GSE154775/HS2/")

GSE154775_HS_2 <- CreateSeuratObject(counts = Data,project = "GSE154775", min.cells = 3, min.features = 200)
GSE154775_HS_2$sample <- "GSE154775_HS_2"
GSE154775_HS_2$sample_details <- metadata$Sample_characteristics_ch1[2]
GSE154775_HS_2$sample_sources <- metadata$Sample_source_name_ch1[2]
rm(Data)

```


```{r run filter and doubletfinder}
###############################################################################################################################################
#########################################RUN DOUBLET FINDER#########################################################################

#RUN DOUBLET FINDER ON ALL THE SAMPLES INDIVIDUALLY. yOU CAN RUN A LOOPE ON ALL DATASETS
#GSE154775_HS_1

Data <- GSE154775_HS_1
Data$percent.mt <- PercentageFeatureSet(object = Data, pattern = "^MT-")
colnames(Data@meta.data)[2] <- "nUMI"
colnames(Data@meta.data)[3] <- "nGene"

#QC and Filter
VlnPlot(object = Data, features = c("nUMI", "nGene", "percent.mt"), pt.size = 0.1)
Data
table(Data@meta.data$orig.ident)
# Filter out low quality cells using selected thresholds - these will change with experiment

#note check with doublet finder to find cutt-off
Data_filtered <- subset(x = Data, 
                        subset= (nUMI >= 500) & 
                          (nGene >= 500) & 
                          (nGene <= 5000) &
                          ( percent.mt < 20))
Data_filtered
table(Data_filtered@meta.data$orig.ident)


# pre-process standard workflow
Data_filtered <- NormalizeData(object = Data_filtered)
Data_filtered <- FindVariableFeatures(object = Data_filtered)
Data_filtered <- ScaleData(object = Data_filtered)
Data_filtered <- RunPCA(object = Data_filtered)
ElbowPlot(Data_filtered,ndims = 30)
Data_filtered <- FindNeighbors(object = Data_filtered, dims = 1:22)
Data_filtered <- FindClusters(object = Data_filtered)
Data_filtered <- RunUMAP(object = Data_filtered, dims = 1:22)

## pK Identification (no ground-truth) ---------------------------------------------------------------------------------------
sweep.res.list <- paramSweep_v3(Data_filtered, PCs = 1:22, sct = FALSE)
sweep.stats <- summarizeSweep(sweep.res.list, GT = FALSE)
bcmvn <- find.pK(sweep.stats)

ggplot(bcmvn, aes(pK, BCmetric, group = 1)) +
  geom_point() +
  geom_line()

pK <- bcmvn %>% # select the pK that corresponds to max bcmvn to optimize doublet detection
  filter(BCmetric == max(BCmetric)) %>%
  select(pK) 
pK <- as.numeric(as.character(pK[[1]]))

## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
annotations <- Data_filtered@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)           ## ex: annotations <- seu_kidney@meta.data$ClusteringResults

### edit the fraction of expected doublets
nExp_poi <- round(0.046*nrow(Data_filtered@meta.data))  ## Assuming 4.6% doublet formation rate - tailor for your dataset -from illumina   https://kb.10xgenomics.com/hc/en-us/articles/360001378811-What-is-the-maximum-number-of-cells-that-can-be-profiled-
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))

# run doubletFinder 
Data_filtered <- doubletFinder_v3(Data_filtered, 
                                  PCs = 1:22, 
                                  pN = 0.25, 
                                  pK = pK, 
                                  nExp = nExp_poi.adj,
                                  reuse.pANN = FALSE, sct = FALSE)

colnames(Data_filtered@meta.data)[13] <-"Doublets"
# visualize doublets
DimPlot(Data_filtered, reduction = 'umap', group.by = "Doublets")


# number of singlets and doublets
table(Data_filtered@meta.data$Doublets)

GSE154775_HS_1_DF <- Data_filtered
```


```{r merge all data}

## Merge all datasets together; add a prefix to cell names to avoid barcode collisions between samples.
# Cell barcodes can overlap between studies, so renaming helps distinguish their origin.
HS_all_DF <- merge(GSE15477_all, y = c(GSE155850_all, gtg349_HS_raw_DF, UCSF_HS_K_DF), add.cell.ids = c("GSE15477","GSE155850","gtg349","UCSF"), project = "HS_single_cell")

# Filter the merged dataset to exclude doublets and retain only singlet cells for downstream analysis.
HS_all_singlets <- subset(HS_all_DF, subset = Doublets == "Singlet")

# Quality Control visualization for filtered data (singlets only)
# Violin plots for nUMI (total UMIs per cell), nGene (number of genes per cell), and percent.mt (percent mitochondrial genes)
VlnPlot(object = HS_all_singlets, features = c("nUMI", "nGene", "percent.mt"), pt.size = 0.1)

# Standard single-cell RNA-seq workflow steps:
# 1. Normalize expression data
HS_all_singlets <- NormalizeData(HS_all_singlets)
# 2. Identify highly variable genes/features
HS_all_singlets <- FindVariableFeatures(HS_all_singlets)
# 3. Scale data for downstream analyses
HS_all_singlets <- ScaleData(HS_all_singlets)
# 4. Run Principal Component Analysis for dimensionality reduction
HS_all_singlets <- RunPCA(HS_all_singlets)
# 5. Generate an 'elbow plot' to visualize variance explained by the first 50 PCs, select appropriate number for UMAP
ElbowPlot(HS_all_singlets, ndims = 50)
# 6. Compute UMAP embedding using first 40 principal components
HS_all_singlets <- RunUMAP(HS_all_singlets, dims = 1:40, reduction = 'pca')

# Visualize UMAP before integration; group cells by their original dataset (orig.ident), without rasterization
before <- DimPlot(HS_all_singlets, reduction = 'umap', group.by = 'orig.ident', raster = FALSE)
```


```{r harmony integration and defining clusters}

# run Harmony using variable we want to integrate on - study, sample, individual, etc
HS_all_singlets.harmony <- HS_all_singlets %>% RunHarmony(group.by.vars = c('orig.ident','sample','tissue'), plot_convergence = FALSE)

HS_all_singlets.harmony.embed <- Embeddings(HS_all_singlets.harmony, "harmony")


# Do UMAP and clustering using ** Harmony embeddings instead of PCA **
HS_all_singlets.harmony <- HS_all_singlets.harmony %>%
  RunUMAP(reduction = 'harmony', dims = 1:40) 

HS_all_singlets.harmony <- FindNeighbors(HS_all_singlets.harmony, reduction = "harmony", dims = 1:40) 

#cluster at different resolutions
HS_all_singlets.harmony <- FindClusters(HS_all_singlets.harmony,resolution = seq(from=0.1, to = 0.7, by = 0.1), verbose = FALSE)

#umap values are updated when we run harmony
#Look at clustree to decide on resoution to use.
#resolution us determined expected number of clusters and how they look in clustree
library(clustree)
tree <- clustree(HS_all_singlets.harmony, prefix = "RNA_snn_res.")

# visualize after integration
after <- DimPlot(HS_all_singlets.harmony, reduction = 'umap', group.by = 'orig.ident', raster = FALSE)

before|after

DimPlot(HS_all_singlets.harmony, reduction = 'umap',raster = FALSE, split.by = "orig.ident", label = TRUE, repel = TRUE)

```


```{r cluster_annotatation}

#the resolution decided to define clusters
Idents(HS_all_singlets.harmony) <- "RNA_snn_res.1.2"


#umap with new clusters
DimPlot(HS_all_singlets.harmony, reduction = 'umap',raster = FALSE)

#to identify markers for these clusters
RNA_markers <- FindAllMarkers(object = HS_all_singlets.harmony, 
                              only.pos = TRUE,
                              logfc.threshold = 0.25,
                              min.pct = 0.1, verbose =TRUE) 

#save these and share with stakeholder for annotation


write.table(RNA_markers, "RNA_markers_at resolution_1.2.csv", row.names = TRUE,col.names = TRUE, sep = "," )

#add annotations as provided by stake holder

HS_all_singlets.harmony <-  RenameIdents(object = HS_all_singlets.harmony,"0" = "Basal Keratinocyte1",
                                         "1" = "Spinous layer keratinocytes",
                                         "2" = "TCell_CD4_TFH",
                                         "3" = "Interfollicular spinous layer keratinocytes-2",
                                         "4" = "Dendritic cell",
                                         "5" = "Dermal fibroblast",
                                         "6" = "Endothelial cell",
                                         "7" = "CD8 T cells",
                                         "8" = "Interfollicular mitotic keratinocytes",
                                         "9" = "Spinous layer keratinocytes",
                                         "10" = "CD14+ CCL3hi IL1Bhi epidermal macrophages",
                                         "11" = "Melanocytes",
                                         "12" = "Keratinocytes expressing ion channels",
                                         "13" = "Langerhans cells",
                                         "14" = "Granular layer keratinocytes",
                                         "15" = "Smooth muscle signature",
                                         "16" = "Differentiated upper hair follicle keratinocytes",
                                         "17" = "Differentiated upper hair follicle keratinocytes",
                                         "18" = "Interfollicular KRT17+ basal keratinocytes",
                                         "19" = "Langerhans cells",
                                         "20" = "Interfollicular spinous layer keratinocytes-S100",
                                         "21" = "Plasma cell",
                                         "22" = "Basal Keratinocyte1",
                                         "23" = "Vein endothelial cell",
                                         "24" = "CD1C+CD301A+ epidermal myeloid DC",
                                         "25" = "B Cells",
                                         "26" = "Cycling_S_M_phase",
                                         "27" = "Dermal fibroblast",
                                         "28" = "Mast cell",
                                         "29" = "Spinous layer keratinocytes",
                                         "30" = "Interfollicular KRT17+ basal keratinocytes",
                                         "31" = "Endothelial cell",
                                         "32" = "NK",
                                         "33" = "TCell_CD4_TH1",
                                         "34" = "Unasigned")

#save this to metadata fo seurat object.
HS_all_singlets.harmony$Cluster_annotations <- Idents(HS_all_singlets.harmony)

#plot dimplot
DimPlot(HS_all_singlets.harmony, raster = FALSE, label = TRUE, repel = TRUE)

```